project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - articles/index.qmd
    - population_parameter_and_sample_statistic/population_and_samples.ipynb
    - probability_illusions_flips_in_a_row/flip_heads_in_a_row.ipynb

website:
  title: "Reinventing the Wheel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: articles/index.qmd
        text: Articles

format:
  html:
    theme: cosmo
    toc: true

jupyter: rtw