<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paolo Coraggio">
<meta name="dcterms.date" content="2026-04-29">
<meta name="description" content="Not all fouls are created equal. Some are more equal than others.">

<title>The Foul, the Card and the Gap – Reinventing the Wheel</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Reinventing the Wheel</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../articles/index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../claude.html"> 
<span class="menu-text">Claude and I</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-foul-the-card-and-the-gap" id="toc-the-foul-the-card-and-the-gap" class="nav-link active" data-scroll-target="#the-foul-the-card-and-the-gap">The Foul, the Card and the Gap</a>
  <ul class="collapse">
  <li><a href="#previously-on" id="toc-previously-on" class="nav-link" data-scroll-target="#previously-on">Previously on</a></li>
  <li><a href="#why-this-metric-and-why-it-is-not-simple" id="toc-why-this-metric-and-why-it-is-not-simple" class="nav-link" data-scroll-target="#why-this-metric-and-why-it-is-not-simple">Why this metric, and why it is not simple</a></li>
  <li><a href="#two-ways-to-measure-the-same-thing" id="toc-two-ways-to-measure-the-same-thing" class="nav-link" data-scroll-target="#two-ways-to-measure-the-same-thing">Two ways to measure the same thing</a></li>
  <li><a href="#visualizing-the-rate" id="toc-visualizing-the-rate" class="nav-link" data-scroll-target="#visualizing-the-rate">Visualizing the rate</a></li>
  <li><a href="#the-statistical-problem-why-the-tools-we-have-are-not-enough" id="toc-the-statistical-problem-why-the-tools-we-have-are-not-enough" class="nav-link" data-scroll-target="#the-statistical-problem-why-the-tools-we-have-are-not-enough">The statistical problem: why the tools we have are not enough</a></li>
  <li><a href="#proportion-tests-building-the-intuition" id="toc-proportion-tests-building-the-intuition" class="nav-link" data-scroll-target="#proportion-tests-building-the-intuition">Proportion tests: building the intuition</a>
  <ul class="collapse">
  <li><a href="#a-brief-and-not-entirely-unjustified-historical-detour" id="toc-a-brief-and-not-entirely-unjustified-historical-detour" class="nav-link" data-scroll-target="#a-brief-and-not-entirely-unjustified-historical-detour">A brief and not entirely unjustified historical detour</a></li>
  <li><a href="#the-model-and-the-reality-each-foul-is-a-bernoulli-trial" id="toc-the-model-and-the-reality-each-foul-is-a-bernoulli-trial" class="nav-link" data-scroll-target="#the-model-and-the-reality-each-foul-is-a-bernoulli-trial">The model and the reality: each foul is a Bernoulli trial</a></li>
  <li><a href="#how-the-z-test-for-proportions-works" id="toc-how-the-z-test-for-proportions-works" class="nav-link" data-scroll-target="#how-the-z-test-for-proportions-works">How the z-test for proportions works</a></li>
  </ul></li>
  <li><a href="#bootstrap-building-confidence-from-the-data-itself" id="toc-bootstrap-building-confidence-from-the-data-itself" class="nav-link" data-scroll-target="#bootstrap-building-confidence-from-the-data-itself">Bootstrap: building confidence from the data itself</a></li>
  <li><a href="#full-league-analysis-which-teams-stand-out" id="toc-full-league-analysis-which-teams-stand-out" class="nav-link" data-scroll-target="#full-league-analysis-which-teams-stand-out">Full league analysis: which teams stand out?</a></li>
  <li><a href="#the-per-match-rate" id="toc-the-per-match-rate" class="nav-link" data-scroll-target="#the-per-match-rate">The per-match rate</a></li>
  <li><a href="#across-leagues" id="toc-across-leagues" class="nav-link" data-scroll-target="#across-leagues">Across leagues</a></li>
  <li><a href="#back-to-the-scatter-plot" id="toc-back-to-the-scatter-plot" class="nav-link" data-scroll-target="#back-to-the-scatter-plot">Back to the scatter plot</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#appendix-a-note-on-donald-ransom-whitney" id="toc-appendix-a-note-on-donald-ransom-whitney" class="nav-link" data-scroll-target="#appendix-a-note-on-donald-ransom-whitney">Appendix: a note on Donald Ransom Whitney</a>
  <ul class="collapse">
  <li><a href="#appendix---the-data" id="toc-appendix---the-data" class="nav-link" data-scroll-target="#appendix---the-data">Appendix - the data</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Foul, the Card and the Gap</h1>
  <div class="quarto-categories">
    <div class="quarto-category">football-in-data</div>
  </div>
  </div>

<div>
  <div class="description">
    Not all fouls are created equal. Some are more equal than others.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Paolo Coraggio </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 29, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="077ec568" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> binom, norm</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> proportions_ztest</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">'./src'</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> discipline_stats <span class="im">import</span> (</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    filter_league_season,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    team_summary,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    rate_summary,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    plot_league_bar,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    plot_forest,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    compare_mean_to_threshold</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="fda82d53" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">'./data/processed/team_matches.pkl'</span>, <span class="st">'rb'</span>) <span class="im">as</span> f:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    team_matches <span class="op">=</span> pickle.load(f)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>serie_a_2425 <span class="op">=</span> team_matches[</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    (team_matches[<span class="st">'league'</span>] <span class="op">==</span> <span class="st">'Serie_A'</span>) <span class="op">&amp;</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    (team_matches[<span class="st">'season'</span>] <span class="op">==</span> <span class="st">'2425'</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Rows: </span><span class="sc">{</span><span class="bu">len</span>(serie_a_2425)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Teams: </span><span class="sc">{</span>serie_a_2425[<span class="st">'team'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Matches per team: </span><span class="sc">{</span><span class="bu">len</span>(serie_a_2425) <span class="op">//</span> serie_a_2425[<span class="st">'team'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 760
Teams: 20
Matches per team: 38</code></pre>
</div>
</div>
<section id="the-foul-the-card-and-the-gap" class="level1">
<h1>The Foul, the Card and the Gap</h1>
<p><em>Not all fouls are created equal. Some are more equal than others.</em></p>
<section id="previously-on" class="level2">
<h2 class="anchored" data-anchor-id="previously-on">Previously on</h2>
<p>In previous notebooks of this series we analysed <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/03_fouls_analysis.ipynb">fouls committed</a> and <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/04_yellow_cards_analysis.ipynb">yellow cards</a> received as separate quantities, using Serie A 2024/25 as our working example. We found that some teams foul significantly more than the league average, and that some teams receive significantly more yellow cards. We also found that the two rankings do not always match.</p>
<p>The scatter plot at the end of the yellow cards notebook made this visible: some teams foul a lot and get relatively few cards, while others foul little and collect many bookings. The two metrics tell different stories about the same matches.</p>
<p>This notebook investigates the gap between them: not how much a team fouls, and not how many cards it receives, but the rate at which fouls become bookings. That rate is the metric that connects the two analyses and, as we will see, measuring it carefully turns out to be less straightforward than it looks.</p>
<p>If you are reading this notebook without the previous ones, all you need to know is this: a team commits roughly 12 fouls per match in Serie A and receives roughly 2 yellow cards. The question is whether that ratio is the same for every team, or whether some teams are systematically more or less likely to be booked for the same foul.</p>
</section>
<section id="why-this-metric-and-why-it-is-not-simple" class="level2">
<h2 class="anchored" data-anchor-id="why-this-metric-and-why-it-is-not-simple">Why this metric, and why it is not simple</h2>
<p>The most natural way to connect fouls and yellow cards is to ask: out of every foul committed, how often does the referee reach for a card? This is the <strong>conversion rate</strong>, and it has an immediate intuitive appeal. A team that fouls aggressively but rarely gets booked is playing a different game from a team that commits fewer but more reckless challenges. The raw counts cannot tell those stories apart. The rate can.</p>
<p>But the rate is not a neutral measurement. It is a compound of at least three things: how a team plays, how the referee interprets the laws of the game, and the interaction between the two. Before we compute anything, it is worth being precise about what the metric can and cannot tell us.</p>
<p><strong>Within a single league and season</strong>, the referee pool is roughly shared. Every team faces the same set of officials over 38 matches, with some rotation. Systematic differences in the rate between teams are therefore more likely to reflect team behaviour than referee behaviour. A team with a consistently high conversion rate across many different referees is probably doing something that earns cards regardless of who is officiating.</p>
<p><strong>Across different leagues</strong>, the picture is more complicated. We already showed in the fouls notebook that Italian referees call nearly three more fouls per match than English ones, while the number of yellow cards per match is almost identical in both leagues. This means the denominator of our rate, fouls committed, is itself referee-dependent. A higher conversion rate in one league might mean referees apply a stricter threshold for showing a card, or it might mean the fouls being called are of a different nature: softer, more frequent, less card-worthy. The metric cannot separate these explanations on its own.</p>
<p>The honest summary: within a league, the rate is primarily a team signal. Across leagues, it is a compound of team behaviour and referee culture, and interpreting it requires care.</p>
<p>This notebook focuses on the within-league question first. We will move to the cross-league comparison at the end, with the appropriate caveats. Future notebooks in the series will use multi-season and national versus international data to try to isolate the referee effect more cleanly.</p>
</section>
<section id="two-ways-to-measure-the-same-thing" class="level2">
<h2 class="anchored" data-anchor-id="two-ways-to-measure-the-same-thing">Two ways to measure the same thing</h2>
<p>Before we run any tests, we need to decide how to compute the rate. This is not a technical detail. It is a measurement choice that affects every number that follows, and the two most natural approaches give different answers.</p>
<p><strong>Approach 1: ratio of totals (crude rate)</strong></p>
<p>Add up all the yellow cards a team received across the season. Divide by the total number of fouls committed. One number per team, computed from the season totals.</p>
<p>This is the simplest version of the metric and the easiest to communicate: Verona committed 475 fouls and received 94 yellow cards, so their conversion rate is 94/475 = 0.198, roughly one booking every five fouls.</p>
<p><strong>Approach 2: mean of per-match ratios</strong></p>
<p>For each match, compute the ratio of yellow cards to fouls committed. Then take the average of those match-level ratios across the season.</p>
<p>This treats each match as an independent observation. A match where a team commits 2 fouls and receives 1 yellow card contributes a ratio of 0.5, regardless of how many fouls the team commits in other matches.</p>
<p><strong>Why they differ</strong></p>
<p>The two approaches weight matches differently. The ratio of totals gives more weight to high-foul matches, because those matches contribute more to the denominator. The mean of per-match ratios treats every match equally regardless of how many fouls were committed.</p>
<p>Neither is universally correct. The ratio of totals is more stable and less sensitive to outlier matches with very few fouls. The mean of per-match ratios is more representative of the typical match experience but can be distorted by matches where the denominator is very small: a team that commits 1 foul and receives 1 yellow card contributes a ratio of 1.0, which may not be meaningful.</p>
<p>We will compute both, compare them, and choose one for the main analysis. The choice will be explicit and justified.</p>
<div id="45ddc249" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rate_df <span class="op">=</span> rate_summary(serie_a_2425, numerator<span class="op">=</span><span class="st">'yellow_cards'</span>, denominator<span class="op">=</span><span class="st">'fouls_committed'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rate_df <span class="op">=</span> rate_df.sort_values(<span class="st">'ratio_of_totals'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>rate_df[<span class="st">'fouls_per_card_total'</span>] <span class="op">=</span> rate_df[<span class="st">'total_denominator'</span>] <span class="op">/</span> rate_df[<span class="st">'total_numerator'</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>rate_df[<span class="st">'fouls_per_card_mean'</span>]  <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> rate_df[<span class="st">'mean_ratio'</span>]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League totals: </span><span class="sc">{</span>serie_a_2425[<span class="st">'yellow_cards'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.0f}</span><span class="ss"> yellow cards, "</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>serie_a_2425[<span class="st">'fouls_committed'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.0f}</span><span class="ss"> fouls"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League crude rate: "</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>serie_a_2425[<span class="st">'yellow_cards'</span>]<span class="sc">.</span><span class="bu">sum</span>() <span class="op">/</span> serie_a_2425[<span class="st">'fouls_committed'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.4f}</span><span class="ss"> - inverse: </span><span class="sc">{</span> serie_a_2425[<span class="st">'fouls_committed'</span>]<span class="sc">.</span><span class="bu">sum</span>() <span class="op">/</span>serie_a_2425[<span class="st">'yellow_cards'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.4f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(rate_df[[<span class="st">'team'</span>, <span class="st">'total_numerator'</span>, <span class="st">'total_denominator'</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>               <span class="st">'ratio_of_totals'</span>, <span class="st">'fouls_per_card_total'</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>               <span class="st">'mean_ratio'</span>, <span class="st">'fouls_per_card_mean'</span>]].to_string(index<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>League totals: 1452 yellow cards, 9501 fouls
League crude rate: 0.1528 - inverse: 6.5434

      team  total_numerator  total_denominator  ratio_of_totals  fouls_per_card_total  mean_ratio  fouls_per_card_mean
     Lazio             92.0              424.0         0.216981              4.608696    0.218175             4.583474
Fiorentina             81.0              440.0         0.184091              5.432099    0.211161             4.735713
     Parma             74.0              405.0         0.182716              5.472973    0.195564             5.113403
     Monza             90.0              511.0         0.176125              5.677778    0.182611             5.476116
      Como             87.0              497.0         0.175050              5.712644    0.186911             5.350130
    Torino             80.0              480.0         0.166667              6.000000    0.174943             5.716159
     Milan             68.0              415.0         0.163855              6.102941    0.179671             5.565741
    Verona             94.0              579.0         0.162349              6.159574    0.174358             5.735327
      Roma             64.0              405.0         0.158025              6.328125    0.159710             6.261351
   Udinese             84.0              536.0         0.156716              6.380952    0.160040             6.248419
  Atalanta             67.0              434.0         0.154378              6.477612    0.154306             6.480636
   Venezia             76.0              503.0         0.151093              6.618421    0.160130             6.244908
     Genoa             71.0              496.0         0.143145              6.985915    0.148393             6.738878
     Inter             57.0              414.0         0.137681              7.263158    0.138963             7.196165
  Juventus             66.0              481.0         0.137214              7.287879    0.143240             6.981285
  Cagliari             68.0              500.0         0.136000              7.352941    0.139676             7.159413
     Lecce             60.0              465.0         0.129032              7.750000    0.129267             7.735950
    Empoli             66.0              566.0         0.116608              8.575758    0.118679             8.426106
   Bologna             61.0              535.0         0.114019              8.770492    0.115328             8.670943
    Napoli             46.0              415.0         0.110843              9.021739    0.105997             9.434267</code></pre>
</div>
</div>
<p>The table also shows the inverse, i.e.&nbsp;fouls per card, which is often easier to read: Lazio concedes a booking every 4.6 fouls; Napoli, every 9.4.</p>
<p>The two approaches agree closely for most teams: the ratio of totals and the mean of per-match ratios differ by no more than 0.01 for the majority. This is reassuring. When the two methods give similar answers, the measurement is stable and not sensitive to the choice of approach.</p>
<p>The league crude rate is 0.153: roughly one yellow card every six and a half fouls. But the team-level variation is substantial. Lazio converts one foul in every 4.6 into a booking (rate 0.217). Napoli converts one in every nine (rate 0.111). That is nearly a factor of two between the top and bottom of the table.</p>
<p>Notice something immediately: the rate ranking looks very different from the fouls ranking. Lazio was one of the least fouling teams in the league. Empoli and Bologna were among the most fouling. Yet here, Lazio sits at the top and Empoli and Bologna sit near the bottom. The scatter plot anomaly we identified in the yellow cards notebook is now a number.</p>
<p>The two measurement approaches differ most for Fiorentina (0.184 vs 0.211) and Napoli (0.111 vs 0.106). For Fiorentina, the mean of per-match ratios is higher, suggesting that in matches where they committed few fouls, a higher proportion became cards. For Napoli, the ratio of totals (0.111) is marginally higher than the mean of per-match ratios (0.106), suggesting that in matches where they committed more fouls, a slightly higher proportion became cards. Both differences are small and may simply reflect match-to-match variation rather than a systematic pattern.</p>
<p>For the main analysis we will use the <strong>ratio of totals</strong>. It is more stable, less sensitive to low-foul matches, and easier to interpret as a season-level summary. We keep the mean of per-match ratios available for comparison.</p>
</section>
<section id="visualizing-the-rate" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-rate">Visualizing the rate</h2>
<p>Before running any tests, we look at the rate visually. The bar chart shows each team’s conversion rate relative to the league average, using the ratio of totals. The scatter plot anomalies from the previous notebook should now have a clear numerical form.</p>
<div id="1d95bf5d" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>league_rate <span class="op">=</span> serie_a_2425[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> serie_a_2425[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>rate_df[<span class="st">'diff_from_league'</span>] <span class="op">=</span> rate_df[<span class="st">'ratio_of_totals'</span>] <span class="op">-</span> league_rate</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> sns.axes_style(<span class="st">"whitegrid"</span>):</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">7</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    ax.set_facecolor(<span class="st">'#f0f0f0'</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [<span class="st">'tomato'</span> <span class="cf">if</span> x <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">'steelblue'</span> <span class="cf">for</span> x <span class="kw">in</span> rate_df[<span class="st">'diff_from_league'</span>]]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    ax.barh(rate_df[<span class="st">'team'</span>], rate_df[<span class="st">'diff_from_league'</span>], color<span class="op">=</span>colors, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    ax.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Difference from league average conversion rate'</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Yellow cards per foul: team deviation from league average — Serie A 2024/25'</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    ax.invert_yaxis()</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League average conversion rate: </span><span class="sc">{</span>league_rate<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the_foul_the_card_and_the_gap_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>League average conversion rate: 0.1528</code></pre>
</div>
</div>
<p>The chart tells a cleaner story than either the fouls or yellow cards charts did individually.</p>
<p>Lazio stands alone at the top, more than 0.06 above the league average. That is not a small gap: the league average rate is 0.153, and Lazio sits at 0.217. They are converting fouls into bookings at a rate roughly 40% above the league norm.</p>
<p>Fiorentina and Parma follow, both around 0.03 above average. Then a cluster of teams between 0.01 and 0.025 above: Monza, Como, Torino, Milan, Verona. At the other end, Napoli, Bologna and Empoli sit furthest below the line, all more than 0.035 below average.</p>
<p>If we compare this ranking to the <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/03_fouls_analysis.ipynb">fouls ranking from the same season and leauge</a>, Verona was the most fouling team in the league. Here they sit in the middle of the pack. Lazio was one of the least fouling teams. Here they lead. The rate is doing exactly what it was designed to do: separating how much a team fouls from how often those fouls escalate.</p>
<p>The visual is suggestive. But a bar chart shows differences, not significance. The question is whether these gaps are real in the statistical sense, or whether they fall within the range of what random variation can produce over a 38-match season. That is what the tests are for.</p>
</section>
<section id="the-statistical-problem-why-the-tools-we-have-are-not-enough" class="level2">
<h2 class="anchored" data-anchor-id="the-statistical-problem-why-the-tools-we-have-are-not-enough">The statistical problem: why the tools we have are not enough</h2>
<p>When dealing with fouls, their distribution allowed us to use t-tests for hypothesis testing. With yellow cards, the data turned out to be non-normal, so we added Mann-Whitney and permutation tests. Each time, the data forced us to upgrade the toolkit.</p>
<p>The rate presents a different problem.</p>
<p>A conversion rate is not a mean of continuous measurements. It is a proportion: out of a total of <span class="math inline">\(n\)</span> fouls, <span class="math inline">\(k\)</span> resulted in a yellow card. The simplest model for this kind of data is the <strong><em>binomial distribution</em></strong>, not the Gaussian, and it is a reasonable place to start. The Poisson, which served us well for modelling yellow card counts, is not the right tool here: it models the number of events in a fixed interval with no upper bound, whereas the binomial models successes out of a fixed number of trials. We have a fixed number of trials. We know <span class="math inline">\(n\)</span>. A team committed 424 fouls and received 92 yellow cards. We want to know whether a conversion rate of 92/424 = 0.217 is surprising given that the league average is 0.153.</p>
<p>This is a different question from “is this team’s mean foul count different from the rest?” It is asking whether a particular number of successes in a fixed number of trials is consistent with a given underlying probability. The t-test was not designed for this. Mann-Whitney was not designed for this either: it compares rank orderings, not binomial outcomes.</p>
<p>We need proportion tests. There are two main ones, and they approach the same question from different angles.</p>
<p>The <strong>z-test for proportions</strong> uses a normal approximation: when <span class="math inline">\(n\)</span> is large enough, the binomial distribution is approximately Gaussian, and we can compute a standard error and a z-score. Fast, simple, and accurate when <span class="math inline">\(n\)</span> is large and <span class="math inline">\(p\)</span> is not too close to 0 or 1.</p>
<p>The <strong>exact binomial test</strong> makes no normal approximation. It computes the exact probability of observing <span class="math inline">\(k\)</span> or more successes in <span class="math inline">\(n\)</span> trials under the null hypothesis. Slower to compute, but exact. Preferred when <span class="math inline">\(n\)</span> is small or <span class="math inline">\(p\)</span> is extreme.</p>
<p>We will use both, compare them, and introduce bootstrap as a third verification. The pattern by now should be familiar: when multiple approaches agree, the conclusion is solid.</p>
</section>
<section id="proportion-tests-building-the-intuition" class="level2">
<h2 class="anchored" data-anchor-id="proportion-tests-building-the-intuition">Proportion tests: building the intuition</h2>
<section id="a-brief-and-not-entirely-unjustified-historical-detour" class="level3">
<h3 class="anchored" data-anchor-id="a-brief-and-not-entirely-unjustified-historical-detour">A brief and not entirely unjustified historical detour</h3>
<p>We have already met a brewer (Gosset), a chemist (Wilcoxon), an esteemed math professor (Henry Mann) and his doctoral student (Whitney, who did most of the work and got second billing on the paper, as doctoral students do). The proportion test has a less colourful origin story, but an older one.</p>
<p>The foundations of proportion testing trace back to <a href="https://en.wikipedia.org/wiki/Pierre-Simon_Laplace">Pierre-Simon Laplace</a>, a man whose talent for surviving political upheaval was, if anything, slightly more impressive than his talent for mathematics. Laplace worked through the French Revolution, the Terror, Napoleon’s rise and fall, and the Restoration without ever finding himself on the wrong side of whoever was currently in power. Fourier, who knew him well, reportedly described him as a weathervane. Between regime changes, he found time to build a rigorous theory of probability.</p>
<p>Among other things, Laplace used what we would now recognise as a z-test for proportions to analyse birth records in Paris and London, asking whether the observed ratio of male to female births was consistent with an equal underlying probability. It was not, and Laplace was precise about the uncertainty in his conclusion. This was 1778. The mathematics had nothing to do with politics, which was presumably a relief.</p>
<p>The exact binomial test has an even older pedigree. <a href="https://en.wikipedia.org/wiki/Jacob_Bernoulli">Jacob Bernoulli</a> described the binomial distribution in his <em>Ars Conjectandi</em>, published posthumously in 1713. Bernoulli spent twenty years working on it and died before it was finished. The idea that you could compute the exact probability of <span class="math inline">\(k\)</span> successes in <span class="math inline">\(n\)</span> independent trials with fixed probability <span class="math inline">\(p\)</span> was one of the foundational results of probability theory. It took twenty years and one death to get there, which in retrospect seems like a lot for something that fits in half a line of code.</p>
<p>So the tools we are about to use are older than the t-test by more than a century. They were developed not for football data but for the same reason all statistical tools were developed: someone had a real question, imperfect data, and needed a principled way to separate signal from noise.</p>
</section>
<section id="the-model-and-the-reality-each-foul-is-a-bernoulli-trial" class="level3">
<h3 class="anchored" data-anchor-id="the-model-and-the-reality-each-foul-is-a-bernoulli-trial">The model and the reality: each foul is a Bernoulli trial</h3>
<p>Start with the simplest possible experiment: a coin flip. Two outcomes, one probability. Call heads a success and tails a failure. The probability of success is <span class="math inline">\(p = 0.5\)</span>, and nothing requires it to stay there. A biased coin with <span class="math inline">\(p = 0.3\)</span> is still a Bernoulli trial. So is a coin with <span class="math inline">\(p = 0.1528\)</span>.</p>
<p>That last number is the Serie A 2024/25 conversion rate. A foul is a Bernoulli trial where success means a yellow card. The referee either reaches for the card or does not.</p>
<p>Before writing down the model formally, it is worth reminding <strong><em>what a model is</em></strong>. In statistics as in physics, a model is always an approximation of reality. The binomial model says that each of Lazio’s 424 fouls is an independent flip of the same biased coin, with a fixed probability <span class="math inline">\(p\)</span> of producing a card. We know this is not literally true. The probability that a foul becomes a card depends on the referee, the scoreline, the match situation, whether the player argues, and half a dozen other things. <span class="math inline">\(p\)</span> is not constant. The fouls are not independent.</p>
<p>And yet the model is useful. When we aggregate across a full season, 38 matches and hundreds of fouls, the noise from all those varying conditions averages out. What remains is a stable rate. The model is wrong at the level of individual fouls and approximately right at the level of the season. This is a recurring pattern in the series: events that are part of a messy, entangled process turn out to be well described by a model that assumes independence. It is not obvious that this should work. It does, and the rest of this notebook shows how far it takes us.</p>
<p>Under this model, a team that commits <span class="math inline">\(n\)</span> fouls and receives <span class="math inline">\(k\)</span> yellow cards has an observed rate <span class="math inline">\(\hat{p} = k/n\)</span>, and the total number of cards follows a Binomial distribution:</p>
<p><span class="math display">\[K \sim \text{Binomial}(n,\ p)\]</span></p>
<p>A natural question at this point is whether the association between fouls and yellow cards can be measured directly, rather than assumed. At match level, a simple regression of cards on fouls committed would tell us whether matches with more fouls tend to produce more cards. We have everything we need for that. What we cannot do with this data is model the conversion probability of an individual foul, because we only observe match totals, not individual fouls. That would require a different dataset entirely: one row per foul, with features like the match situation, the referee, and the type of challenge. A logistic regression on that data would estimate how each feature shifts the probability of a card being issued. It would also show how much of the variation in conversion rates is explained by team behaviour versus referee tendency, which is exactly the decomposition we cannot make here. For now, the Bernoulli model with a fixed <span class="math inline">\(p\)</span> is the right level of complexity for the data we have.</p>
</section>
<section id="how-the-z-test-for-proportions-works" class="level3">
<h3 class="anchored" data-anchor-id="how-the-z-test-for-proportions-works">How the z-test for proportions works</h3>
<p>The idea is straightforward. We have a team with a known number of fouls and yellow cards. We want to know whether their conversion rate is surprisingly different from the league average. We treat <strong><em>each foul as a trial</em></strong>, and <strong><em>each yellow card as a success</em></strong>.</p>
<p>Under the null hypothesis, the probability of a success on any given foul is equal to the league average rate <span class="math inline">\(p = 0.153\)</span>. The question is: given that Lazio committed 424 fouls, how surprising is it to observe 92 yellow cards, i.e.&nbsp;an observed conversion rate of <span class="math inline">\(\hat{p} = 0.217\)</span>?</p>
<p>The z-test answers this by computing how many standard deviations the observed rate sits away from the expected rate. The standard error of a proportion is:</p>
<p><span class="math display">\[SE = \sqrt{\frac{p(1-p)}{n}}\]</span></p>
<p>where <span class="math inline">\(p\)</span> is the null rate and <span class="math inline">\(n\)</span> is the number of trials (i.e.&nbsp;the number of fouls). The z-score is:</p>
<p><span class="math display">\[z = \frac{\hat{p} - p}{SE}\]</span></p>
<p>where <span class="math inline">\(\hat{p}\)</span> is the observed rate. If the absolute value of z is large, the observed rate is far from what we would expect by chance.</p>
<p>Let us compute this by hand for Lazio first, then verify with scipy.</p>
<div id="7060cc6a" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.stats.proportion <span class="im">import</span> proportions_ztest</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># League reference rate</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>p_null <span class="op">=</span> serie_a_2425[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> serie_a_2425[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Lazio's numbers</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>lazio <span class="op">=</span> rate_df[rate_df[<span class="st">'team'</span>] <span class="op">==</span> <span class="st">'Lazio'</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="bu">int</span>(lazio[<span class="st">'total_denominator'</span>])</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="bu">int</span>(lazio[<span class="st">'total_numerator'</span>])</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> k <span class="op">/</span> n</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: standard error</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> np.sqrt(p_null <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_null) <span class="op">/</span> n)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: z-score</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (p_hat <span class="op">-</span> p_null) <span class="op">/</span> se</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: two-sided p-value</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>p_z <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> norm.cdf(<span class="bu">abs</span>(z)))</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Lazio: </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss"> yellow cards in </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss"> fouls"</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Observed rate:  </span><span class="sc">{</span>p_hat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League rate:    </span><span class="sc">{</span>p_null<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Standard error: </span><span class="sc">{</span>se<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"z-score:        </span><span class="sc">{</span>z<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"p-value (z-test): </span><span class="sc">{</span>p_z<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Verify with statsmodels</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>z_sm, p_sm <span class="op">=</span> proportions_ztest(k, n, p_null)</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"statsmodels verification: z=</span><span class="sc">{</span>z_sm<span class="sc">:.4f}</span><span class="ss">, p=</span><span class="sc">{</span>p_sm<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lazio: 92 yellow cards in 424 fouls
Observed rate:  0.2170
League rate:    0.1528
Standard error: 0.0175
z-score:        3.6714
p-value (z-test): 0.0002

statsmodels verification: z=3.2049, p=0.0014</code></pre>
</div>
</div>
<p>The manual calculation and statsmodels agree on the direction and significance but give different z-scores and p-values. This is worth understanding rather than glossing over.</p>
<p>Our calculation uses the null rate (0.153) in the standard error formula:</p>
<p><span class="math display">\[SE = \sqrt{\frac{p_0(1-p_0)}{n}}\]</span></p>
<p>This is the standard one-sample proportion test: we are asking how surprising the observed rate is if the true rate were the league average.</p>
<p><code>statsmodels</code> library uses a slightly different convention by default, computing the standard error from the observed rate rather than the null rate. This is more common in two-sample tests where there is no fixed reference. For a one-sample test against a known reference rate, our manual version is the correct formulation.</p>
<p>Both return a highly significant result. Lazio’s z-score of 3.67 means their observed rate sits nearly four standard deviations above the league average. The p-value of 0.0002 means that if the true rate were the league average, we would observe a deviation this large in fewer than 2 matches out of 10,000 seasons. The result is not on the boundary. It is emphatic.</p>
<p>Now let us run the exact binomial test as a verification, making no normal approximation at all.</p>
<div id="5eea8404" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>p_binom <span class="op">=</span> binom.sf(k <span class="op">-</span> <span class="dv">1</span>, n, p_null)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>p_binom_twosided <span class="op">=</span> <span class="bu">min</span>(<span class="dv">1</span>, <span class="dv">2</span> <span class="op">*</span> p_binom)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Exact binomial test (one-sided):   p=</span><span class="sc">{</span>p_binom<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Exact binomial test (two-sided):   p=</span><span class="sc">{</span>p_binom_twosided<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># scipy verification</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> stats.binomtest(k, n, p_null, alternative<span class="op">=</span><span class="st">'two-sided'</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scipy binomtest verification:      p=</span><span class="sc">{</span>result<span class="sc">.</span>pvalue<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Exact binomial test (one-sided):   p=0.0003
Exact binomial test (two-sided):   p=0.0006

scipy binomtest verification:      p=0.0004</code></pre>
</div>
</div>
<p>Both the z-test and the exact binomial test agree: Lazio’s conversion rate is highly significant. The exact binomial p-value of 0.0004 makes no normal approximation. It computes the exact probability of observing 92 or more yellow cards in 424 fouls if the true rate were the league average. That probability is very small.</p>
<p>The small discrepancy between our manual two-sided p-value (0.0006) and scipy’s (0.0004) reflects a difference in how the two tails are summed. Our version doubles the one-sided p-value, which is a common approximation. Scipy sums all outcomes with probability at most as likely as the observed one in both directions, which is more precise. For results this far from the null, the difference is irrelevant. For borderline cases it can matter, which is a reason to prefer scipy’s implementation in production.</p>
<p>The z-test and the exact binomial test tell the same story here, which is reassuring. The z-test is appropriate because n=424 is large and p=0.153 is not extreme, so the normal approximation is reliable. When n is small or p is close to 0 or 1, the exact binomial is the safer choice.</p>
<p>We now have the tools. Let us apply them to the full league.</p>
</section>
</section>
<section id="bootstrap-building-confidence-from-the-data-itself" class="level2">
<h2 class="anchored" data-anchor-id="bootstrap-building-confidence-from-the-data-itself">Bootstrap: building confidence from the data itself</h2>
<p>The z-test and the exact binomial test both test against a fixed null rate: the league average. They answer the question “is this team’s rate surprising given the league average?” But they say nothing about the uncertainty in the estimate itself. How wide is the range of plausible values for Lazio’s true conversion rate? If we repeated the season with the same teams and referees, how much would the rate vary?</p>
<p>This is where the bootstrap comes in. Instead of deriving a confidence interval from a formula, we estimate it empirically by resampling the data we already have.</p>
<p>The idea is disarmingly simple. It is nor really “disarmingly simple”, but using it makes you look smarter.</p>
<p>Lazio played 38 matches. We treat those 38 matches as our best available description of Lazio’s underlying behaviour. We then ask: if we reshuffled those 38 matches like a deck of cards, drew 38 again at random (with replacement, meaning the same match can appear more than once), and computed the conversion rate, what would we get? We repeat this thousands of times. Each repetition gives a slightly different rate, because each resample is a slightly different deck. The <em>distribution of those rates</em> is our empirical estimate of how much Lazio’s rate <em>would vary</em> if the season were replayed with the same underlying behaviour.</p>
<p>The bootstrap makes no assumption about the shape of that distribution. It does not need the binomial approximation or the normal approximation. It just asks the data directly. One of its key advantages is that it quantifies how much the estimate would vary around its central value, with no assumptions required.</p>
<p>This is not the same as the permutation test introduced in <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/04_yellow_cards_analysis.ipynb">the yellow cards analysis</a>. The permutation test shuffled labels to test a null hypothesis. The bootstrap resamples from the observed data to estimate uncertainty. Both are resampling methods. They answer different questions. <em>The permutation test shuffled labels to test a null hypothesis. The bootstrap resamples from the observed data to estimate uncertainty. Both are resampling methods. They answer different questions.</em></p>
<div id="cc1250d3" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>n_bootstrap <span class="op">=</span> <span class="dv">10_000</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>lazio_matches <span class="op">=</span> serie_a_2425[serie_a_2425[<span class="st">'team'</span>] <span class="op">==</span> <span class="st">'Lazio'</span>].copy()</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>bootstrap_rates <span class="op">=</span> []</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(n_bootstrap):</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    sample <span class="op">=</span> lazio_matches.sample(n<span class="op">=</span><span class="bu">len</span>(lazio_matches), replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    rate <span class="op">=</span> sample[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> sample[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    bootstrap_rates.append(rate)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>bootstrap_rates <span class="op">=</span> np.array(bootstrap_rates)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>ci_low, ci_high <span class="op">=</span> np.percentile(bootstrap_rates, [<span class="fl">2.5</span>, <span class="fl">97.5</span>])</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> sns.axes_style(<span class="st">"whitegrid"</span>):</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    ax.set_facecolor(<span class="st">'#f0f0f0'</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    ax.hist(bootstrap_rates, bins<span class="op">=</span><span class="dv">50</span>, color<span class="op">=</span><span class="st">'steelblue'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, edgecolor<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    ax.axvline(p_hat, color<span class="op">=</span><span class="st">'tomato'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f'Observed rate (</span><span class="sc">{</span>p_hat<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    ax.axvline(p_null, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, linestyle<span class="op">=</span><span class="st">'--'</span>,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>               label<span class="op">=</span><span class="ss">f'League average (</span><span class="sc">{</span>p_null<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    ax.axvline(ci_low, color<span class="op">=</span><span class="st">'steelblue'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>               label<span class="op">=</span><span class="ss">f'95% CI [</span><span class="sc">{</span>ci_low<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_high<span class="sc">:.3f}</span><span class="ss">]'</span>)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    ax.axvline(ci_high, color<span class="op">=</span><span class="st">'steelblue'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, linestyle<span class="op">=</span><span class="st">':'</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Bootstrap conversion rate'</span>)</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Count'</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Bootstrap distribution — Lazio conversion rate'</span>)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Observed rate:        </span><span class="sc">{</span>p_hat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Bootstrap mean:       </span><span class="sc">{</span>bootstrap_rates<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Bootstrap std:        </span><span class="sc">{</span>bootstrap_rates<span class="sc">.</span>std()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI:               [</span><span class="sc">{</span>ci_low<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>ci_high<span class="sc">:.4f}</span><span class="ss">]"</span>)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League average:       </span><span class="sc">{</span>p_null<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"League average in CI: </span><span class="sc">{</span>ci_low <span class="op">&lt;=</span> p_null <span class="op">&lt;=</span> ci_high<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the_foul_the_card_and_the_gap_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Observed rate:        0.2170
Bootstrap mean:       0.2168
Bootstrap std:        0.0173
95% CI:               [0.1832, 0.2506]
League average:       0.1528
League average in CI: False</code></pre>
</div>
</div>
<p>The bootstrap is computationally heavier than the z-test or the exact binomial: thousands of resamples instead of one formula. As we say when <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/04_yellow_cards_analysis.ipynb">dealing with yellow cards</a> this is similar to the tradeoff from the permutation test. The logic is the same: flexibility costs compute. On a dataset this size the difference is negligible, but the principle matters: when a simpler model’s assumptions hold, use it. When they do not, the bootstrap is there.</p>
<p>The bootstrap distribution is approximately bell-shaped and centred tightly around the observed rate of 0.217. The 95% confidence interval runs from 0.183 to 0.251: we are 95% confident that Lazio’s true underlying conversion rate sits somewhere in that range.</p>
<p>The league average of 0.153 is nowhere near the interval. It sits far to the left of the entire bootstrap distribution, which confirms what the proportion tests already told us: Lazio’s rate is not consistent with the league average. The confidence interval and the hypothesis test are two sides of the same coin. When the null value falls outside the 95% confidence interval, the two-sided p-value is below 0.05. Both are true here, and by a wide margin.</p>
<p>Notice also that the bootstrap standard deviation (0.0173) is very close to the standard error we computed manually for the z-test (0.0175). This is not a coincidence. When the bootstrap works well, it recovers the same uncertainty estimate as the analytical formula. The fact that they agree here is a validation of both approaches.</p>
<p>The bootstrap adds something the proportion tests cannot: a picture of the full distribution of plausible values. We know Lazio’s rate is significantly above average, and we know that “significantly above average” means somewhere between 0.183 and 0.251 with 95% confidence. That range is the practical answer to the question of how unusual Lazio really are.</p>
<p>We now have three tools that agree: z-test, exact binomial, and bootstrap. Time to run them across the full league.</p>
</section>
<section id="full-league-analysis-which-teams-stand-out" class="level2">
<h2 class="anchored" data-anchor-id="full-league-analysis-which-teams-stand-out">Full league analysis: which teams stand out?</h2>
<p>We have validated the toolkit on Lazio. Now we run the same three tests for every team in the league: z-test for proportions, exact binomial, and bootstrap confidence interval. The reference rate for each test is the league average computed from all other teams, not including the team being tested. This is the same one-versus-rest logic we used in the fouls and yellow cards notebooks.</p>
<div id="7b5fd315" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> discipline_stats <span class="im">import</span> compare_mean_to_threshold</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>results_rate <span class="op">=</span> []</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, row <span class="kw">in</span> rate_df.iterrows():</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    team_name <span class="op">=</span> row[<span class="st">'team'</span>]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">'total_denominator'</span>])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">'total_numerator'</span>])</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    p_hat <span class="op">=</span> k <span class="op">/</span> n</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Reference rate: rest of league</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    rest <span class="op">=</span> serie_a_2425[serie_a_2425[<span class="st">'team'</span>] <span class="op">!=</span> team_name]</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    p_ref <span class="op">=</span> rest[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> rest[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Z-test</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    z, p_z <span class="op">=</span> proportions_ztest(k, n, p_ref)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Exact binomial</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    p_binom <span class="op">=</span> stats.binomtest(k, n, p_ref, alternative<span class="op">=</span><span class="st">'two-sided'</span>).pvalue</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Bootstrap</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    team_data <span class="op">=</span> serie_a_2425[serie_a_2425[<span class="st">'team'</span>] <span class="op">==</span> team_name]</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>    boot_rates <span class="op">=</span> []</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10_000</span>):</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>        sample <span class="op">=</span> team_data.sample(n<span class="op">=</span><span class="bu">len</span>(team_data), replace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>        boot_rates.append(sample[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> sample[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>())</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>    boot_rates <span class="op">=</span> np.array(boot_rates)</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>    ci_low, ci_high <span class="op">=</span> np.percentile(boot_rates, [<span class="fl">2.5</span>, <span class="fl">97.5</span>])</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>    ref_in_ci <span class="op">=</span> ci_low <span class="op">&lt;=</span> p_ref <span class="op">&lt;=</span> ci_high</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>    results_rate.append({</span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">'team'</span>: team_name,</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">'n_fouls'</span>: n,</span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">'n_cards'</span>: k,</span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">'rate'</span>: <span class="bu">round</span>(p_hat, <span class="dv">4</span>),</span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>        <span class="st">'ref_rate'</span>: <span class="bu">round</span>(p_ref, <span class="dv">4</span>),</span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">'diff'</span>: <span class="bu">round</span>(p_hat <span class="op">-</span> p_ref, <span class="dv">4</span>),</span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">'z_p'</span>: <span class="bu">round</span>(p_z, <span class="dv">4</span>),</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">'binom_p'</span>: <span class="bu">round</span>(p_binom, <span class="dv">4</span>),</span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>        <span class="st">'ci_low'</span>: <span class="bu">round</span>(ci_low, <span class="dv">4</span>),</span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a>        <span class="st">'ci_high'</span>: <span class="bu">round</span>(ci_high, <span class="dv">4</span>),</span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>        <span class="st">'ref_in_ci'</span>: ref_in_ci,</span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a>        <span class="st">'sig_z'</span>: p_z <span class="op">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a>        <span class="st">'sig_binom'</span>: p_binom <span class="op">&lt;</span> <span class="fl">0.05</span></span>
<span id="cb14-46"><a href="#cb14-46" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb14-47"><a href="#cb14-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-48"><a href="#cb14-48" aria-hidden="true" tabindex="-1"></a>results_rate_df <span class="op">=</span> pd.DataFrame(results_rate).sort_values(<span class="st">'rate'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb14-49"><a href="#cb14-49" aria-hidden="true" tabindex="-1"></a>results_display <span class="op">=</span> results_rate_df.rename(columns<span class="op">=</span>{</span>
<span id="cb14-50"><a href="#cb14-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_fouls'</span>: <span class="st">'Fouls'</span>,</span>
<span id="cb14-51"><a href="#cb14-51" aria-hidden="true" tabindex="-1"></a>    <span class="st">'n_cards'</span>: <span class="st">'Cards'</span>,</span>
<span id="cb14-52"><a href="#cb14-52" aria-hidden="true" tabindex="-1"></a>    <span class="st">'rate'</span>: <span class="st">'Rate'</span>,</span>
<span id="cb14-53"><a href="#cb14-53" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ref_rate'</span>: <span class="st">'Ref rate'</span>,</span>
<span id="cb14-54"><a href="#cb14-54" aria-hidden="true" tabindex="-1"></a>    <span class="st">'diff'</span>: <span class="st">'Diff'</span>,</span>
<span id="cb14-55"><a href="#cb14-55" aria-hidden="true" tabindex="-1"></a>    <span class="st">'z_p'</span>: <span class="st">'p (z-test)'</span>,</span>
<span id="cb14-56"><a href="#cb14-56" aria-hidden="true" tabindex="-1"></a>    <span class="st">'binom_p'</span>: <span class="st">'p (binomial)'</span>,</span>
<span id="cb14-57"><a href="#cb14-57" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ci_low'</span>: <span class="st">'CI low'</span>,</span>
<span id="cb14-58"><a href="#cb14-58" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ci_high'</span>: <span class="st">'CI high'</span>,</span>
<span id="cb14-59"><a href="#cb14-59" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ref_in_ci'</span>: <span class="st">'Ref in CI'</span>,</span>
<span id="cb14-60"><a href="#cb14-60" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_z'</span>: <span class="st">'Sig (z)'</span>,</span>
<span id="cb14-61"><a href="#cb14-61" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_binom'</span>: <span class="st">'Sig (binom)'</span></span>
<span id="cb14-62"><a href="#cb14-62" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb14-63"><a href="#cb14-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-64"><a href="#cb14-64" aria-hidden="true" tabindex="-1"></a>results_display</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">team</th>
<th data-quarto-table-cell-role="th">Fouls</th>
<th data-quarto-table-cell-role="th">Cards</th>
<th data-quarto-table-cell-role="th">Rate</th>
<th data-quarto-table-cell-role="th">Ref rate</th>
<th data-quarto-table-cell-role="th">Diff</th>
<th data-quarto-table-cell-role="th">p (z-test)</th>
<th data-quarto-table-cell-role="th">p (binomial)</th>
<th data-quarto-table-cell-role="th">CI low</th>
<th data-quarto-table-cell-role="th">CI high</th>
<th data-quarto-table-cell-role="th">Ref in CI</th>
<th data-quarto-table-cell-role="th">Sig (z)</th>
<th data-quarto-table-cell-role="th">Sig (binom)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Lazio</td>
<td>424</td>
<td>92</td>
<td>0.2170</td>
<td>0.1498</td>
<td>0.0672</td>
<td>0.0008</td>
<td>0.0002</td>
<td>0.1832</td>
<td>0.2506</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Fiorentina</td>
<td>440</td>
<td>81</td>
<td>0.1841</td>
<td>0.1513</td>
<td>0.0328</td>
<td>0.0760</td>
<td>0.0622</td>
<td>0.1527</td>
<td>0.2158</td>
<td>False</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Parma</td>
<td>405</td>
<td>74</td>
<td>0.1827</td>
<td>0.1515</td>
<td>0.0312</td>
<td>0.1040</td>
<td>0.0831</td>
<td>0.1435</td>
<td>0.2242</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Monza</td>
<td>511</td>
<td>90</td>
<td>0.1761</td>
<td>0.1515</td>
<td>0.0246</td>
<td>0.1440</td>
<td>0.1229</td>
<td>0.1481</td>
<td>0.2063</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Como</td>
<td>497</td>
<td>87</td>
<td>0.1751</td>
<td>0.1516</td>
<td>0.0235</td>
<td>0.1689</td>
<td>0.1501</td>
<td>0.1419</td>
<td>0.2122</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Torino</td>
<td>480</td>
<td>80</td>
<td>0.1667</td>
<td>0.1521</td>
<td>0.0146</td>
<td>0.3915</td>
<td>0.3735</td>
<td>0.1371</td>
<td>0.1972</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Milan</td>
<td>415</td>
<td>68</td>
<td>0.1639</td>
<td>0.1523</td>
<td>0.0115</td>
<td>0.5256</td>
<td>0.4950</td>
<td>0.1255</td>
<td>0.2041</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Verona</td>
<td>579</td>
<td>94</td>
<td>0.1623</td>
<td>0.1522</td>
<td>0.0101</td>
<td>0.5082</td>
<td>0.4877</td>
<td>0.1318</td>
<td>0.1952</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Roma</td>
<td>405</td>
<td>64</td>
<td>0.1580</td>
<td>0.1526</td>
<td>0.0054</td>
<td>0.7645</td>
<td>0.7301</td>
<td>0.1232</td>
<td>0.1954</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Udinese</td>
<td>536</td>
<td>84</td>
<td>0.1567</td>
<td>0.1526</td>
<td>0.0041</td>
<td>0.7929</td>
<td>0.7642</td>
<td>0.1303</td>
<td>0.1845</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Atalanta</td>
<td>434</td>
<td>67</td>
<td>0.1544</td>
<td>0.1528</td>
<td>0.0016</td>
<td>0.9253</td>
<td>0.8940</td>
<td>0.1261</td>
<td>0.1831</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Venezia</td>
<td>503</td>
<td>76</td>
<td>0.1511</td>
<td>0.1529</td>
<td>-0.0018</td>
<td>0.9088</td>
<td>0.9507</td>
<td>0.1224</td>
<td>0.1818</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Genoa</td>
<td>496</td>
<td>71</td>
<td>0.1431</td>
<td>0.1534</td>
<td>-0.0102</td>
<td>0.5160</td>
<td>0.5749</td>
<td>0.1178</td>
<td>0.1702</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Inter</td>
<td>414</td>
<td>57</td>
<td>0.1377</td>
<td>0.1535</td>
<td>-0.0158</td>
<td>0.3498</td>
<td>0.4132</td>
<td>0.1043</td>
<td>0.1732</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Juventus</td>
<td>481</td>
<td>66</td>
<td>0.1372</td>
<td>0.1537</td>
<td>-0.0164</td>
<td>0.2946</td>
<td>0.3431</td>
<td>0.1054</td>
<td>0.1717</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>Cagliari</td>
<td>500</td>
<td>68</td>
<td>0.1360</td>
<td>0.1538</td>
<td>-0.0178</td>
<td>0.2466</td>
<td>0.2920</td>
<td>0.1063</td>
<td>0.1711</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>Lecce</td>
<td>465</td>
<td>60</td>
<td>0.1290</td>
<td>0.1541</td>
<td>-0.0250</td>
<td>0.1076</td>
<td>0.1399</td>
<td>0.1034</td>
<td>0.1552</td>
<td>True</td>
<td>False</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>Empoli</td>
<td>566</td>
<td>66</td>
<td>0.1166</td>
<td>0.1551</td>
<td>-0.0385</td>
<td>0.0043</td>
<td>0.0105</td>
<td>0.0869</td>
<td>0.1475</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>Bologna</td>
<td>535</td>
<td>61</td>
<td>0.1140</td>
<td>0.1551</td>
<td>-0.0411</td>
<td>0.0028</td>
<td>0.0085</td>
<td>0.0880</td>
<td>0.1408</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>Napoli</td>
<td>415</td>
<td>46</td>
<td>0.1108</td>
<td>0.1547</td>
<td>-0.0439</td>
<td>0.0044</td>
<td>0.0119</td>
<td>0.0886</td>
<td>0.1321</td>
<td>False</td>
<td>True</td>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The table separates signal from noise. Of the twenty teams in Serie A 2024/25, sixteen sit close enough to the league average that the tests cannot distinguish their rates from random variation. Four teams stand out.</p>
<p>Lazio converts fouls into yellow cards at a rate of 0.217, roughly one foul in every 4.6 results in a booking. The league average is one in 6.5. Both the z-test and the exact binomial agree: this is not a fluke (p &lt; 0.01). The bootstrap confidence interval [0.183, 0.251] sits entirely above the league average of 0.153.</p>
<p>At the other end, Empoli, Bologna, and Napoli foul regularly but collect relatively few cards. Empoli’s rate of 0.112 and Bologna’s 0.117 are significantly below average by both tests. Napoli fouls less than most sides and still shows up as a significan outlier below the average, converting at 0.111.</p>
<p>Notice that the z-test and the exact binomial always agree on direction and broadly agree on magnitude. They should: with sample sizes between 300 and 550 fouls per team, the normal approximation to the binomial is reliable, and the two tests are equivalent in this regime. The exact binomial is the safer default regardless, because it makes no approximation.</p>
<p>The bootstrap confidence intervals tell the same story as the hypothesis tests but add something the p-values do not: a sense of scale. Lazio’s interval is wide (0.068 across), reflecting genuine uncertainty in the point estimate. A p-value of 0.0002 can give a false impression of precision; the interval is the honest version.</p>
<p>What the table cannot tell us is why these teams differ. The rate is a compound signal: team behaviour, referee tendency, and their interaction. We will return to that question in the next section.</p>
</section>
<section id="the-per-match-rate" class="level2">
<h2 class="anchored" data-anchor-id="the-per-match-rate">The per-match rate</h2>
<p>The proportion tests treated the entire season as a single binomial experiment: <span class="math inline">\(k\)</span> yellow cards in <span class="math inline">\(n\)</span> fouls. That is the ratio-of-totals approach from the measurement section.</p>
<p>The second approach treats each match as an independent observation and works with the distribution of per-match rates: yellow cards divided by fouls committed in that match. This is a different object. A team that consistently converts 15% of its fouls in every match looks identical to one that alternates between 5% and 25%, if you only look at the season aggregate. The per-match distribution can tell them apart.</p>
<p>Two tests are natural for per-match rates. Mann-Whitney makes no assumptions about the shape of the distribution (remember, it asks whether one team’s per-match rates tend to be systematically higher or lower than the rest of the league). A t-test makes stronger assumptions (approximately normal per-match rates) but is easier to interpret and gives a useful comparison: if the two tests agree, the normality assumption is probably not hurting us.</p>
<div id="56265541" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>serie_a_2425 <span class="op">=</span> serie_a_2425.copy()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>serie_a_2425[<span class="st">'match_rate'</span>] <span class="op">=</span> serie_a_2425[<span class="st">'yellow_cards'</span>] <span class="op">/</span> serie_a_2425[<span class="st">'fouls_committed'</span>].replace(<span class="dv">0</span>, np.nan)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="66c21917" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> mannwhitneyu, ttest_ind</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>pm_results <span class="op">=</span> []</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> team_name <span class="kw">in</span> serie_a_2425[<span class="st">'team'</span>].unique():</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    team_rates <span class="op">=</span> serie_a_2425.loc[serie_a_2425[<span class="st">'team'</span>] <span class="op">==</span> team_name, <span class="st">'match_rate'</span>].dropna()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    rest_rates <span class="op">=</span> serie_a_2425.loc[serie_a_2425[<span class="st">'team'</span>] <span class="op">!=</span> team_name, <span class="st">'match_rate'</span>].dropna()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    _, p_mw  <span class="op">=</span> mannwhitneyu(team_rates, rest_rates, alternative<span class="op">=</span><span class="st">'two-sided'</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    _, p_t   <span class="op">=</span> ttest_ind(team_rates, rest_rates, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    pm_results.append({</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">'team'</span>:        team_name,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'mean_rate'</span>:   team_rates.mean(),</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p_mw'</span>:        p_mw,</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p_t'</span>:         p_t,</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">'sig_mw'</span>:      p_mw <span class="op">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">'sig_t'</span>:       p_t  <span class="op">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>pm_df <span class="op">=</span> pd.DataFrame(pm_results).sort_values(<span class="st">'mean_rate'</span>, ascending<span class="op">=</span><span class="va">False</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="898a61d9" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>display_pm <span class="op">=</span> pm_df.rename(columns<span class="op">=</span>{</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'team'</span>:      <span class="st">'Team'</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'mean_rate'</span>: <span class="st">'Mean per-match rate'</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p_mw'</span>:      <span class="st">'p (Mann-Whitney)'</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p_t'</span>:       <span class="st">'p (Welch t-test)'</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_mw'</span>:    <span class="st">'Sig MW'</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig_t'</span>:     <span class="st">'Sig t'</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>display_pm[[<span class="st">'Team'</span>, <span class="st">'Mean per-match rate'</span>, <span class="st">'p (Mann-Whitney)'</span>, <span class="st">'p (Welch t-test)'</span>, <span class="st">'Sig MW'</span>, <span class="st">'Sig t'</span>]]<span class="op">\</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    .style.<span class="bu">format</span>({<span class="st">'Mean per-match rate'</span>: <span class="st">'</span><span class="sc">{:.3f}</span><span class="st">'</span>, <span class="st">'p (Mann-Whitney)'</span>: <span class="st">'</span><span class="sc">{:.4f}</span><span class="st">'</span>, <span class="st">'p (Welch t-test)'</span>: <span class="st">'</span><span class="sc">{:.4f}</span><span class="st">'</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<style type="text/css">
</style>

<table id="T_a5767" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_a5767_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Team</th>
<th id="T_a5767_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Mean per-match rate</th>
<th id="T_a5767_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">p (Mann-Whitney)</th>
<th id="T_a5767_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p (Welch t-test)</th>
<th id="T_a5767_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Sig MW</th>
<th id="T_a5767_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">Sig t</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_a5767_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">0</th>
<td id="T_a5767_row0_col0" class="data row0 col0">Lazio</td>
<td id="T_a5767_row0_col1" class="data row0 col1">0.218</td>
<td id="T_a5767_row0_col2" class="data row0 col2">0.0003</td>
<td id="T_a5767_row0_col3" class="data row0 col3">0.0037</td>
<td id="T_a5767_row0_col4" class="data row0 col4">True</td>
<td id="T_a5767_row0_col5" class="data row0 col5">True</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">1</th>
<td id="T_a5767_row1_col0" class="data row1 col0">Fiorentina</td>
<td id="T_a5767_row1_col1" class="data row1 col1">0.211</td>
<td id="T_a5767_row1_col2" class="data row1 col2">0.0139</td>
<td id="T_a5767_row1_col3" class="data row1 col3">0.0582</td>
<td id="T_a5767_row1_col4" class="data row1 col4">True</td>
<td id="T_a5767_row1_col5" class="data row1 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">2</th>
<td id="T_a5767_row2_col0" class="data row2 col0">Parma</td>
<td id="T_a5767_row2_col1" class="data row2 col1">0.196</td>
<td id="T_a5767_row2_col2" class="data row2 col2">0.1049</td>
<td id="T_a5767_row2_col3" class="data row2 col3">0.1584</td>
<td id="T_a5767_row2_col4" class="data row2 col4">False</td>
<td id="T_a5767_row2_col5" class="data row2 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">3</th>
<td id="T_a5767_row3_col0" class="data row3 col0">Como</td>
<td id="T_a5767_row3_col1" class="data row3 col1">0.187</td>
<td id="T_a5767_row3_col2" class="data row3 col2">0.2725</td>
<td id="T_a5767_row3_col3" class="data row3 col3">0.2030</td>
<td id="T_a5767_row3_col4" class="data row3 col4">False</td>
<td id="T_a5767_row3_col5" class="data row3 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">4</th>
<td id="T_a5767_row4_col0" class="data row4 col0">Monza</td>
<td id="T_a5767_row4_col1" class="data row4 col1">0.183</td>
<td id="T_a5767_row4_col2" class="data row4 col2">0.1712</td>
<td id="T_a5767_row4_col3" class="data row4 col3">0.2238</td>
<td id="T_a5767_row4_col4" class="data row4 col4">False</td>
<td id="T_a5767_row4_col5" class="data row4 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row5" class="row_heading level0 row5" data-quarto-table-cell-role="th">5</th>
<td id="T_a5767_row5_col0" class="data row5 col0">Milan</td>
<td id="T_a5767_row5_col1" class="data row5 col1">0.180</td>
<td id="T_a5767_row5_col2" class="data row5 col2">0.5156</td>
<td id="T_a5767_row5_col3" class="data row5 col3">0.4049</td>
<td id="T_a5767_row5_col4" class="data row5 col4">False</td>
<td id="T_a5767_row5_col5" class="data row5 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row6" class="row_heading level0 row6" data-quarto-table-cell-role="th">6</th>
<td id="T_a5767_row6_col0" class="data row6 col0">Torino</td>
<td id="T_a5767_row6_col1" class="data row6 col1">0.175</td>
<td id="T_a5767_row6_col2" class="data row6 col2">0.3334</td>
<td id="T_a5767_row6_col3" class="data row6 col3">0.4076</td>
<td id="T_a5767_row6_col4" class="data row6 col4">False</td>
<td id="T_a5767_row6_col5" class="data row6 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row7" class="row_heading level0 row7" data-quarto-table-cell-role="th">7</th>
<td id="T_a5767_row7_col0" class="data row7 col0">Verona</td>
<td id="T_a5767_row7_col1" class="data row7 col1">0.174</td>
<td id="T_a5767_row7_col2" class="data row7 col2">0.4036</td>
<td id="T_a5767_row7_col3" class="data row7 col3">0.4422</td>
<td id="T_a5767_row7_col4" class="data row7 col4">False</td>
<td id="T_a5767_row7_col5" class="data row7 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row8" class="row_heading level0 row8" data-quarto-table-cell-role="th">8</th>
<td id="T_a5767_row8_col0" class="data row8 col0">Venezia</td>
<td id="T_a5767_row8_col1" class="data row8 col1">0.160</td>
<td id="T_a5767_row8_col2" class="data row8 col2">0.9437</td>
<td id="T_a5767_row8_col3" class="data row8 col3">0.9863</td>
<td id="T_a5767_row8_col4" class="data row8 col4">False</td>
<td id="T_a5767_row8_col5" class="data row8 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row9" class="row_heading level0 row9" data-quarto-table-cell-role="th">9</th>
<td id="T_a5767_row9_col0" class="data row9 col0">Udinese</td>
<td id="T_a5767_row9_col1" class="data row9 col1">0.160</td>
<td id="T_a5767_row9_col2" class="data row9 col2">0.6700</td>
<td id="T_a5767_row9_col3" class="data row9 col3">0.9900</td>
<td id="T_a5767_row9_col4" class="data row9 col4">False</td>
<td id="T_a5767_row9_col5" class="data row9 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row10" class="row_heading level0 row10" data-quarto-table-cell-role="th">10</th>
<td id="T_a5767_row10_col0" class="data row10 col0">Roma</td>
<td id="T_a5767_row10_col1" class="data row10 col1">0.160</td>
<td id="T_a5767_row10_col2" class="data row10 col2">0.8071</td>
<td id="T_a5767_row10_col3" class="data row10 col3">0.9944</td>
<td id="T_a5767_row10_col4" class="data row10 col4">False</td>
<td id="T_a5767_row10_col5" class="data row10 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row11" class="row_heading level0 row11" data-quarto-table-cell-role="th">11</th>
<td id="T_a5767_row11_col0" class="data row11 col0">Atalanta</td>
<td id="T_a5767_row11_col1" class="data row11 col1">0.154</td>
<td id="T_a5767_row11_col2" class="data row11 col2">0.9785</td>
<td id="T_a5767_row11_col3" class="data row11 col3">0.7152</td>
<td id="T_a5767_row11_col4" class="data row11 col4">False</td>
<td id="T_a5767_row11_col5" class="data row11 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row12" class="row_heading level0 row12" data-quarto-table-cell-role="th">12</th>
<td id="T_a5767_row12_col0" class="data row12 col0">Genoa</td>
<td id="T_a5767_row12_col1" class="data row12 col1">0.148</td>
<td id="T_a5767_row12_col2" class="data row12 col2">0.8494</td>
<td id="T_a5767_row12_col3" class="data row12 col3">0.3968</td>
<td id="T_a5767_row12_col4" class="data row12 col4">False</td>
<td id="T_a5767_row12_col5" class="data row12 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row13" class="row_heading level0 row13" data-quarto-table-cell-role="th">13</th>
<td id="T_a5767_row13_col0" class="data row13 col0">Juventus</td>
<td id="T_a5767_row13_col1" class="data row13 col1">0.143</td>
<td id="T_a5767_row13_col2" class="data row13 col2">0.2653</td>
<td id="T_a5767_row13_col3" class="data row13 col3">0.3611</td>
<td id="T_a5767_row13_col4" class="data row13 col4">False</td>
<td id="T_a5767_row13_col5" class="data row13 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row14" class="row_heading level0 row14" data-quarto-table-cell-role="th">14</th>
<td id="T_a5767_row14_col0" class="data row14 col0">Cagliari</td>
<td id="T_a5767_row14_col1" class="data row14 col1">0.140</td>
<td id="T_a5767_row14_col2" class="data row14 col2">0.2640</td>
<td id="T_a5767_row14_col3" class="data row14 col3">0.2094</td>
<td id="T_a5767_row14_col4" class="data row14 col4">False</td>
<td id="T_a5767_row14_col5" class="data row14 col5">False</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row15" class="row_heading level0 row15" data-quarto-table-cell-role="th">15</th>
<td id="T_a5767_row15_col0" class="data row15 col0">Inter</td>
<td id="T_a5767_row15_col1" class="data row15 col1">0.139</td>
<td id="T_a5767_row15_col2" class="data row15 col2">0.2308</td>
<td id="T_a5767_row15_col3" class="data row15 col3">0.2978</td>
<td id="T_a5767_row15_col4" class="data row15 col4">False</td>
<td id="T_a5767_row15_col5" class="data row15 col5">False</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row16" class="row_heading level0 row16" data-quarto-table-cell-role="th">16</th>
<td id="T_a5767_row16_col0" class="data row16 col0">Lecce</td>
<td id="T_a5767_row16_col1" class="data row16 col1">0.129</td>
<td id="T_a5767_row16_col2" class="data row16 col2">0.1704</td>
<td id="T_a5767_row16_col3" class="data row16 col3">0.0325</td>
<td id="T_a5767_row16_col4" class="data row16 col4">False</td>
<td id="T_a5767_row16_col5" class="data row16 col5">True</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row17" class="row_heading level0 row17" data-quarto-table-cell-role="th">17</th>
<td id="T_a5767_row17_col0" class="data row17 col0">Empoli</td>
<td id="T_a5767_row17_col1" class="data row17 col1">0.119</td>
<td id="T_a5767_row17_col2" class="data row17 col2">0.0143</td>
<td id="T_a5767_row17_col3" class="data row17 col3">0.0192</td>
<td id="T_a5767_row17_col4" class="data row17 col4">True</td>
<td id="T_a5767_row17_col5" class="data row17 col5">True</td>
</tr>
<tr class="odd">
<th id="T_a5767_level0_row18" class="row_heading level0 row18" data-quarto-table-cell-role="th">18</th>
<td id="T_a5767_row18_col0" class="data row18 col0">Bologna</td>
<td id="T_a5767_row18_col1" class="data row18 col1">0.115</td>
<td id="T_a5767_row18_col2" class="data row18 col2">0.0103</td>
<td id="T_a5767_row18_col3" class="data row18 col3">0.0030</td>
<td id="T_a5767_row18_col4" class="data row18 col4">True</td>
<td id="T_a5767_row18_col5" class="data row18 col5">True</td>
</tr>
<tr class="even">
<th id="T_a5767_level0_row19" class="row_heading level0 row19" data-quarto-table-cell-role="th">19</th>
<td id="T_a5767_row19_col0" class="data row19 col0">Napoli</td>
<td id="T_a5767_row19_col1" class="data row19 col1">0.106</td>
<td id="T_a5767_row19_col2" class="data row19 col2">0.0043</td>
<td id="T_a5767_row19_col3" class="data row19 col3">0.0000</td>
<td id="T_a5767_row19_col4" class="data row19 col4">True</td>
<td id="T_a5767_row19_col5" class="data row19 col5">True</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The two tests mostly agree, but two teams sit in the gap between them, and that gap is informative.</p>
<p>Lazio, Empoli, Bologna and Napoli are significant under both tests and both measurement approaches. The signal for these teams does not depend on which way we measure the rate or which assumptions we make. That is reassuring.</p>
<p>Fiorentina is flagged by Mann-Whitney (p = 0.014) but not by the t-test (p = 0.058). Mann-Whitney tests rank order: it asks whether Fiorentina’s per-match rates tend to sit above those of the rest of the league. The t-test asks whether the means differ, and to answer that question it assumes the per-match rates are approximately normal. When the two tests disagree, it often means the distribution is skewed or has outliers that pull the mean without shifting the bulk of the data. Fiorentina probably has a handful of high-card matches that inflate the mean slightly but are not enough for the t-test to reach significance. Mann-Whitney is the more honest test here.</p>
<p>Lecce is the reverse: the t-test flags it (p = 0.033) while Mann-Whitney does not (p = 0.170). This pattern can arise when a few extreme low-card matches pull the mean down without the bulk of the distribution separating from the rest. In that case, the t-test is reacting to outliers rather than a systematic difference. Mann-Whitney, which ignores the magnitude of the gap and only uses ranks, is again the more conservative and more appropriate choice.</p>
<p>The lesson is not that one test is always better than the other. It is that disagreement between them is a signal worth investigating. For the teams that matter most – Lazio above and Empoli, Bologna, Napoli below – the conclusion is the same regardless of which test we use or which measurement approach we take.</p>
</section>
<section id="across-leagues" class="level2">
<h2 class="anchored" data-anchor-id="across-leagues">Across leagues</h2>
<p>So far we have worked entirely within Serie A. Every comparison has been one team against the rest of the same league, in the same season, facing the same pool of referees. That shared context is what makes the within-league results interpretable as a team signal.</p>
<p>Cross-league comparison is a different problem. If Serie A has a higher conversion rate than the Premier League, there are at least three possible explanations: Serie A players commit fouls that referees are more likely to book; Serie A referees have a lower threshold for issuing cards; or some combination of both. The data cannot separate these. What it can do is describe the difference and give us an honest measure of its size.</p>
<blockquote class="blockquote">
<p>We will compute the crude rate for each league and run a proportion test comparing each league against the rest. The interpretation requires care: a significant result tells us the rates differ, not why.</p>
</blockquote>
<div id="566dc8d1" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>all_2425 <span class="op">=</span> team_matches[</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    (team_matches[<span class="st">'season'</span>] <span class="op">==</span> <span class="st">'2425'</span>) <span class="op">&amp;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    (team_matches[<span class="st">'season_status'</span>] <span class="op">==</span> <span class="st">'complete'</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>league_rates <span class="op">=</span> (</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    all_2425.groupby(<span class="st">'league'</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(<span class="kw">lambda</span> g: pd.Series({</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">'yellow_cards'</span>:   g[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>(),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">'fouls'</span>:          g[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>(),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">'crude_rate'</span>:     g[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> g[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>(),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    }))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    .reset_index()</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    .sort_values(<span class="st">'crude_rate'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>league_rates[<span class="st">'fouls_per_card'</span>] <span class="op">=</span> league_rates[<span class="st">'fouls'</span>] <span class="op">/</span> league_rates[<span class="st">'yellow_cards'</span>]</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(league_rates.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        league  yellow_cards  fouls  crude_rate  fouls_per_card
Premier_League        1539.0 8385.0    0.183542        5.448343
       La_Liga        1703.0 9398.0    0.181209        5.518497
    Bundesliga        1176.0 6532.0    0.180037        5.554422
       Ligue_1        1147.0 7349.0    0.156076        6.407149
       Serie_A        1452.0 9501.0    0.152826        6.543388</code></pre>
</div>
</div>
<div id="85ea277c" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>league_prop_results <span class="op">=</span> []</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, row <span class="kw">in</span> league_rates.iterrows():</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    league_name <span class="op">=</span> row[<span class="st">'league'</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">'yellow_cards'</span>])</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">int</span>(row[<span class="st">'fouls'</span>])</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    rest <span class="op">=</span> all_2425[all_2425[<span class="st">'league'</span>] <span class="op">!=</span> league_name]</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    p_ref <span class="op">=</span> rest[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> rest[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    z, p_z <span class="op">=</span> proportions_ztest(k, n, p_ref)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    p_binom <span class="op">=</span> stats.binomtest(k, n, p_ref, alternative<span class="op">=</span><span class="st">'two-sided'</span>).pvalue</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    league_prop_results.append({</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">'league'</span>:         league_name,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">'crude_rate'</span>:     row[<span class="st">'crude_rate'</span>],</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">'fouls_per_card'</span>: row[<span class="st">'fouls'</span>] <span class="op">/</span> row[<span class="st">'yellow_cards'</span>],</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p_z'</span>:            p_z,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">'p_binom'</span>:        p_binom,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">'sig'</span>:            p_z <span class="op">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>league_prop_df <span class="op">=</span> pd.DataFrame(league_prop_results)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>display(league_prop_df.rename(columns<span class="op">=</span>{</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'league'</span>:         <span class="st">'League'</span>,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'crude_rate'</span>:     <span class="st">'Crude rate'</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'fouls_per_card'</span>: <span class="st">'Fouls per card'</span>,</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p_z'</span>:            <span class="st">'p (z-test)'</span>,</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p_binom'</span>:        <span class="st">'p (exact binomial)'</span>,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sig'</span>:            <span class="st">'Significant'</span>,</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>}).style.<span class="bu">format</span>({<span class="st">'Crude rate'</span>: <span class="st">'</span><span class="sc">{:.3f}</span><span class="st">'</span>, <span class="st">'Fouls per card'</span>: <span class="st">'</span><span class="sc">{:.1f}</span><span class="st">'</span>, <span class="st">'p (z-test)'</span>: <span class="st">'</span><span class="sc">{:.4f}</span><span class="st">'</span>, <span class="st">'p (exact binomial)'</span>: <span class="st">'</span><span class="sc">{:.4f}</span><span class="st">'</span>}))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<style type="text/css">
</style>

<table id="T_f4615" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_f4615_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">League</th>
<th id="T_f4615_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Crude rate</th>
<th id="T_f4615_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Fouls per card</th>
<th id="T_f4615_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">p (z-test)</th>
<th id="T_f4615_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">p (exact binomial)</th>
<th id="T_f4615_level0_col5" class="col_heading level0 col5" data-quarto-table-cell-role="th">Significant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_f4615_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">0</th>
<td id="T_f4615_row0_col0" class="data row0 col0">Premier_League</td>
<td id="T_f4615_row0_col1" class="data row0 col1">0.184</td>
<td id="T_f4615_row0_col2" class="data row0 col2">5.4</td>
<td id="T_f4615_row0_col3" class="data row0 col3">0.0001</td>
<td id="T_f4615_row0_col4" class="data row0 col4">0.0001</td>
<td id="T_f4615_row0_col5" class="data row0 col5">True</td>
</tr>
<tr class="even">
<th id="T_f4615_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">1</th>
<td id="T_f4615_row1_col0" class="data row1 col0">La_Liga</td>
<td id="T_f4615_row1_col1" class="data row1 col1">0.181</td>
<td id="T_f4615_row1_col2" class="data row1 col2">5.5</td>
<td id="T_f4615_row1_col3" class="data row1 col3">0.0005</td>
<td id="T_f4615_row1_col4" class="data row1 col4">0.0003</td>
<td id="T_f4615_row1_col5" class="data row1 col5">True</td>
</tr>
<tr class="odd">
<th id="T_f4615_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">2</th>
<td id="T_f4615_row2_col0" class="data row2 col0">Bundesliga</td>
<td id="T_f4615_row2_col1" class="data row2 col1">0.180</td>
<td id="T_f4615_row2_col2" class="data row2 col2">5.6</td>
<td id="T_f4615_row2_col3" class="data row2 col3">0.0167</td>
<td id="T_f4615_row2_col4" class="data row2 col4">0.0145</td>
<td id="T_f4615_row2_col5" class="data row2 col5">True</td>
</tr>
<tr class="even">
<th id="T_f4615_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">3</th>
<td id="T_f4615_row3_col0" class="data row3 col0">Ligue_1</td>
<td id="T_f4615_row3_col1" class="data row3 col1">0.156</td>
<td id="T_f4615_row3_col2" class="data row3 col2">6.4</td>
<td id="T_f4615_row3_col3" class="data row3 col3">0.0000</td>
<td id="T_f4615_row3_col4" class="data row3 col4">0.0001</td>
<td id="T_f4615_row3_col5" class="data row3 col5">True</td>
</tr>
<tr class="odd">
<th id="T_f4615_level0_row4" class="row_heading level0 row4" data-quarto-table-cell-role="th">4</th>
<td id="T_f4615_row4_col0" class="data row4 col0">Serie_A</td>
<td id="T_f4615_row4_col1" class="data row4 col1">0.153</td>
<td id="T_f4615_row4_col2" class="data row4 col2">6.5</td>
<td id="T_f4615_row4_col3" class="data row4 col3">0.0000</td>
<td id="T_f4615_row4_col4" class="data row4 col4">0.0000</td>
<td id="T_f4615_row4_col5" class="data row4 col5">True</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="b5a5fc1e" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>overall_rate <span class="op">=</span> all_2425[<span class="st">'yellow_cards'</span>].<span class="bu">sum</span>() <span class="op">/</span> all_2425[<span class="st">'fouls_committed'</span>].<span class="bu">sum</span>()</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>league_labels <span class="op">=</span> league_prop_df[<span class="st">'league'</span>].<span class="bu">str</span>.replace(<span class="st">'_'</span>, <span class="st">' '</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>colours <span class="op">=</span> [<span class="st">'#e6a817'</span> <span class="cf">if</span> r <span class="op">&gt;</span> overall_rate <span class="cf">else</span> <span class="st">'#f5d87a'</span> <span class="cf">for</span> r <span class="kw">in</span> league_prop_df[<span class="st">'crude_rate'</span>]]</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(league_labels, league_prop_df[<span class="st">'crude_rate'</span>], color<span class="op">=</span>colours, height<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>ax.axvline(overall_rate, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="fl">1.2</span>, linestyle<span class="op">=</span><span class="st">'--'</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f'Overall average (</span><span class="sc">{</span>overall_rate<span class="sc">:.3f}</span><span class="ss">)'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, rate, fpc <span class="kw">in</span> <span class="bu">zip</span>(bars, league_prop_df[<span class="st">'crude_rate'</span>], league_prop_df[<span class="st">'fouls_per_card'</span>]):</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    ax.text(bar.get_width() <span class="op">+</span> <span class="fl">0.002</span>, bar.get_y() <span class="op">+</span> bar.get_height() <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>            <span class="ss">f'</span><span class="sc">{</span>rate<span class="sc">:.3f}</span><span class="ss"> (</span><span class="sc">{</span>fpc<span class="sc">:.1f}</span><span class="ss"> fouls/card)'</span>, ha<span class="op">=</span><span class="st">'left'</span>, va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Yellow cards per foul (crude rate)'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Yellow card conversion rate by league — 2024/25'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, pad<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="fl">0.26</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="the_foul_the_card_and_the_gap_files/figure-html/cell-15-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>All five leagues differ significantly from the pooled average of the other four. But before reading too much into the p-values, look at the rates themselves.</p>
<p>The five leagues split into two rough groups. Premier League, La Liga and Bundesliga cluster between 0.180 and 0.184, roughly one booking for every 5.5 fouls. Ligue 1 and Serie A sit lower, at 0.156 and 0.153. The gap between the two groups is about three percentage points. With sample sizes of 6,000 to 9,500 fouls per league, even small differences will produce very small p-values. Significance here is almost guaranteed; the question worth asking is whether the difference is meaningful.</p>
<p>What the table cannot tell us is where this gap comes from. A higher conversion rate in the Premier League could mean that Premier League players commit fouls that are more likely to attract a card, maybe more reckless challenges, more dissent, more professional fouls in dangerous positions. It could equally mean that Premier League referees apply a stricter threshold. Or both. The compound signal problem that appeared at team level reappears here at league level, and the data alone cannot decompose it.</p>
<p>The honest reading is this: the rates differ, the difference is consistent across both tests, and the direction is stable. What drives it is a question for a different dataset one that can hold referee identity constant across leagues, or track the same players moving between competitions.</p>
</section>
<section id="back-to-the-scatter-plot" class="level2">
<h2 class="anchored" data-anchor-id="back-to-the-scatter-plot">Back to the scatter plot</h2>
<p>When performing the <a href="https://github.com/pacoraggio/euro-football-discipline-stats/blob/master/notebooks/04_yellow_cards_analysis.ipynb">yellow card analysis</a>, we produces a scatter plot that coloured teams by how far they sat from the diagonal the line of proportional behaviour where more fouls produce proportionally more cards. Two teams sat well above it: Lazio collected far more cards than their foul count would suggest. Two sat well below it: Bologna and Empoli fouled regularly but accumulated few bookings.</p>
<p>That plot was a visual prompt, not a test. The question was whether the pattern would survive scrutiny. It has.</p>
<p>Lazio’s conversion rate of 0.217 is the highest in the league. Both proportion tests and Mann-Whitney flag it as significantly above average. The bootstrap confidence interval [0.183, 0.251] sits entirely above the league rate of 0.153. Whatever is driving Lazio’s bookings, e.g.&nbsp;playing style, referee perception, positional aggression, it is consistent enough across 38 matches to show up clearly in every test we ran.</p>
<p>Bologna and Empoli are the mirror image. Both sit significantly below the league average under all three approaches: z-test, exact binomial, and Mann-Whitney. Bologna converts at 0.117 and Empoli at 0.112. In a league where the average foul produces a card roughly one time in 6.5, these teams are closer to one in nine.</p>
<p>Napoli rounds out the picture. It did not appear in the original scatter plot discussion (its foul count is low enough that it did not stand out visually) but the rate tests surface it clearly as a below-average outlier, significant under all three methods.</p>
<p>The scatter plot asked the right question. The tests confirmed the answer.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>We started with a scatter plot anomaly and ended with a consistent finding across three tests and two measurement approaches. Lazio converts fouls into yellow cards at a rate significantly above the Serie A average; Bologna, Empoli and Napoli sit significantly below it. Sixteen teams are indistinguishable from the league norm. The result is stable: it does not depend on whether we measure the rate as a season aggregate or as a distribution of per-match ratios, and it does not depend on whether we use a parametric test or a non-parametric one.</p>
<p>What we cannot say is why. The conversion rate is a compound signal. It folds together how a team fouls, how referees perceive those fouls, and the interaction between the two. A high rate could mean a team commits fouls in dangerous positions, or with dissent, or against high-profile opponents – all of which attract cards. It could also mean that the referees assigned to a team’s matches happen to be stricter. The data does not separate these explanations.</p>
<p>The cross-league comparison sharpens the limitation. Premier League, La Liga and Bundesliga cluster around 0.181 to 0.184; Ligue 1 and Serie A sit lower at 0.156 and 0.153. The gap is statistically significant and consistent, but it is a compound of team behaviour and referee culture in unknown proportions. A higher rate in the Premier League does not mean Premier League players foul more recklessly. It might. We do not know.</p>
<p>Two questions follow naturally from here. The first is temporal: are Lazio’s rate and Bologna’s rate stable across seasons, or are they artefacts of a single year? A team that appears as an outlier in one season but not in others is a weaker signal than one that sits consistently above or below the average. The second is structural: can we isolate the referee contribution? Referee assignment data, or a dataset that tracks the same players across national and international competitions, would let us begin to decompose the signal. Both questions are tractable. Both are for the next notebook.</p>
<hr>
</section>
<section id="appendix-a-note-on-donald-ransom-whitney" class="level2">
<h2 class="anchored" data-anchor-id="appendix-a-note-on-donald-ransom-whitney">Appendix: a note on Donald Ransom Whitney</h2>
<p>In the Mann-Whitney section we described Whitney as Mann’s doctoral student. A more precise account: Whitney co-published the famous 1947 paper “On a Test of Whether One of Two Random Variables Is Stochastically Larger than the Other” with Mann while still a doctoral candidate at Ohio State University. He completed his PhD two years later, in 1949, with a thesis titled “A Comparison of the Power of Nonparametric Tests and Tests Based on the Normal Distribution Under Nonnormal Alternatives” — an extension of the same work rather than its source.</p>
<p>So he published the result that would carry his name for the rest of statistical history before he had even finished his doctorate. His supervisor presumably signed off on the thesis without excessive scrutiny. Apparently, some things never change in academia.</p>
<p>Source: Mathematics Genealogy Project, https://www.mathgenealogy.org/id.php?id=10179</p>
<section id="appendix---the-data" class="level3">
<h3 class="anchored" data-anchor-id="appendix---the-data">Appendix - the data</h3>
<p>The data used in this notebook comes from <a href="https://www.football-data.co.uk/">football-data.co.uk</a>. A sample-based validation was performed across all datasets, with manual lookup against <a href="https://fbref.com/">fbref.com</a> and <a href="https://www.espn.co.uk/football/">ESPN</a> for flagged outliers.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/pacoraggio\.github\.io\/reinventing-the-wheel\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>